directories:
  output: release/${version}
  buildResources: build
appId: com.electron.desktop
productName: electron
asar: true
copyright: Copyright © 2022 electron
files:
  - filter:
      - ./dist
      - ./package.json
      - ./dist-electron
mac:
  artifactName: ${productName}_${version}.${ext}
  target:
    - dmg
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: ${productName}_${version}.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
publish:
  - provider: generic
    url: http://127.0.0.1:8080
releaseInfo:
  releaseNotes: 版本更新的具体内容
electronVersion: 27.0.2
